org: lens03
app: lens-lambda-fastapi
service: lens-lambda-fastapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
